In [2]:
import numpy as np #numpy를 as(줄여서) np라고 부르겠다

In [3]:
arr = np.array([1,2,3,4])
print(arr)
print(type(arr)) #그냥 배열이랑 넘파이 배열이랑 차이가 많음

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
# 0으로 초기화된 배열
arr = np.zeros((3,3)) # 2차원 벡터
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
# 빈 값으로 만들어진 배열, 기존에 사용한 메모리값이 남아있다.. 초기화 필요
arr = np.empty((4,4))
print(arr)

[[0.00000000e+000 1.29073735e-231 3.95252517e-323 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 1.11253693e-308]]


In [9]:
arr = np.ones((3,3)) # 1값으로 초기화 시킨다, .<-은 실수를 사용할준비가 되어있다_같은타입으로 계산은 속도가 빠르다
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
#배열의 생성
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
# ndarray 배열의 모양, 차수, 데이터 타입 확인, 정수형 타입(.이 없음)
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [22]:
#모양, 몇 차원 확인
arr.shape

(2, 3)

In [23]:
arr.ndim # 차원만 확인

2

In [24]:
arr.dtype # 데이타 타입 확인

dtype('int64')

In [25]:
arr_float = arr.astype(np.float64) #astype()타입을 바꾼다
arr_float.dtype

dtype('float64')

In [26]:
arr_str = np.array(['1','2','3'])
arr_str.dtype

dtype('<U1')

In [28]:
arr_int = arr_str.astype(np.int64) # 문자열 데이터를 인트 타입으로 바꾼다
arr_int.dtype

dtype('int64')

In [30]:
#ndarray 배열의 연산 // 같은자리 차원에 있는 값이 연산된다

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])


In [31]:
arr1 + arr2

array([[ 6,  8],
       [10, 12]])

In [34]:
np.add(arr1,arr2) #np를 활용한 계산

array([[ 6,  8],
       [10, 12]])

In [36]:
np.multiply(arr1,arr2) #np를 활용한 곱셈_ 개인취향대로 사용 할 것

array([[ 5, 12],
       [21, 32]])

In [44]:
# ndarray 배열 슬라이싱 하기 // 배열에서 부분 추출(2차원에서 왼쪽위가 0값, 아래, 오른쪽으로 갈수록 +1)
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
arr_1 = arr[:2,1:3]
print(arr_1)

[[2 3]
 [5 6]]


In [43]:
arr[[0,1,2],[2,0,1]] #세로위치,가로위치 값

array([3, 4, 8])

In [45]:
idx = arr > 3 # idx값에 조건문을 넣는다
print((idx))

[[False False False]
 [ True  True  True]
 [ True  True  True]]


In [46]:
print(arr[idx]) # idx값이 True인것만 재배열 해서 나온다

[4 5 6 7 8 9]


In [4]:
redwine = np.loadtxt(fname='winequality-red.csv',delimiter = ';',skiprows=1) #np에서 csv파일 데이터 가져오기, fname파일이름, delimiter 나누는기준, skiprows 몇줄을 생략할 것인지
print(redwine)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [8]:
print(redwine.sum()) #합계
print(redwine.mean()) #평균

152084.78194
7.926036165311652


In [9]:
# 축(axis)
print(redwine.sum(axis=0))

[13303.1       843.985     433.29     4059.55      139.859   25384.
 74302.       1593.79794  5294.47     1052.38    16666.35     9012.     ]


In [10]:
redwine[:,0] # : 이것만 있으면 전체 데이터를 가르킨다, 0번째 칼럼

array([7.4, 7.8, 7.8, ..., 6.3, 5.9, 6. ])

In [12]:
redwine.max(axis=0)

array([ 15.9    ,   1.58   ,   1.     ,  15.5    ,   0.611  ,  72.     ,
       289.     ,   1.00369,   4.01   ,   2.     ,  14.9    ,   8.     ])